src/components/Common/EditField.vue, src/views/players/EditProfile/EditProfile.vue, src/views/players/EditProfile/components/PlayerAboutMe.vue, src/views/players/EditProfile/components/PlayerEditCredentials.vue, src/views/players/EditProfile/components/PlayerFeaturedAchievement.vue, src/views/players/EditProfile/components/PlayerHeader.vue, src/views/players/EditProfile/components/PlayerHeaderTopRow.vue
Reverts eternagame/eternagame.org#14
=> Revert "fixed styles in Edit Profile page"

package-lock.json, src/store/mobile.vuex.ts, src/types/vue.d.ts, src/views/home/ExperiencedPlayerHome/ExperiencedPlayerHome.vue, src/views/home/ExperiencedPlayerHome/types.ts, src/views/home/NewPlayerHome/NewPlayerHome.vue, src/views/home/NewPlayerHome/types.ts, src/views/players/EditProfile/components/PlayerHeaderImage.vue, src/views/players/EditProfile/components/types.ts, src/views/players/PlayerView/components/PlayerHeaderImage.vue, src/views/players/PlayerView/components/types.ts, src/views/quests/CreateQuest/CreateQuest.vue
- Make Create Quest Page Pixel Perfect according to Mockup
- fix some Typescript errors
- make create quest page pixel perfect according to mockup
- Refactor CSS
- Add template  markup
- Clone application
- Cd into folder and type `npm run serve` in the terminal
- Type the 'Enter button`
- Navigate to `/quests/create` route on the browser
- Earlier pages were not pixel perfect
NA
=> Make Create Quest Page Pixel Perfect according to Mockup

src/types/vue.d.ts
- Fixes TS warning `$http` type
=> fix ts warning on axios type

src/components/PageLayout/EternaPage.vue
Resolves issue with display on Safari
=> replaced page border shadows with background gradients

package-lock.json, package.json, src/components/Sidebar/CalendarPanel.vue, src/locales/en.json, src/views/news/NewsExplore/NewsExplore.vue
https://github.com/eternagame/eternagame.org/issues/44
=> shows date range

package-lock.json, src/types/common-types.ts, src/views/quests/QuestView/QuestView.vue, src/views/quests/QuestView/types.ts
I currently only have QuestView done, I'll probably finish the rest tomorrow.
Choose if you want to merge this as is, or merge everything in a batch.
=> Added types to QuestView

src/components/PageLayout/MobileSidebar.vue
https://github.com/eternagame/eternagame.org/issues/123
=> closes sidenav when page expands

src/components/PageLayout/Navbar/NavbarMenu/NavbarMenuItem.vue, src/components/PageLayout/Navbar/SidebarMenu/SidebarMenuItem.vue, src/utils/utils.ts
https://github.com/eternagame/eternagame.org/issues/105
=> external links open in separate tab

src/views/players/EditProfile/components/EditPlayerAboutMe.vue
https://github.com/eternagame/eternagame.org/issues/160
Change: 
After page reload:
=> simplifies showing user about me text

src/views/news/NewsExplore/NewsExplore.vue
https://github.com/eternagame/eternagame.org/issues/44
=> Make options for news sidebar functional 

src/views/players/EditProfile/EditProfile.vue, src/views/players/EditProfile/components/EditPlayerAboutMe.vue, src/views/players/EditProfile/components/EditPlayerHeader.vue, src/views/players/EditProfile/components/EditPlayerHeaderImage.vue
https://github.com/eternagame/eternagame.org/issues/56
* Makes it possible to change the user image
* Shows preview after uploading file
Before:
Change Image:
After:
TODO https://github.com/eternagame/eternagame.org/issues/159
=> allows user to change profile image

src/components/PageLayout/Navbar/Icons/ChatIcon.vue, src/components/PageLayout/Navbar/Navbar.vue
https://github.com/eternagame/eternagame.org/issues/82
before:
after:
=> shows chat window on all medium screen sizes

src/views/players/LeaderBoard/PlayerCard.vue
https://github.com/eternagame/eternagame.org/issues/145
=> aligns columns

src/assets/chemical_bond.svg, src/components/Cards/PuzzleCard.vue, src/components/Cards/StateCounter.vue
https://github.com/eternagame/eternagame.org/issues/115
Before:
After:
Please make more github issues if any more changes are needed
=> adds energy models and state info to puzzles

src/views/software/SoftwareCard.vue, src/views/software/SoftwareExplore.vue, src/views/software/VersionCard.vue
Do not merge until the following has been resolved with the `/get/?type=software_packages` endpoint:
Major:
- Endpoint should return a list of packages, not a single package
- Software packages need to include the name of the package
Minor:
- Image urls should to resolve to the correct locations (unsure if this is already the case)
- Date should return e.g. "Mar 2019" instead of Unix timestamp
=> Update project model to match server API

src/components/Modals/SoftwareLicenseModal.vue, src/views/software/SoftwareCard.vue, src/views/software/SoftwareExplore.vue, src/views/software/VersionCard.vue
NOTE: This does not yet pull from the `/get/?type=software_packages` endpoint, but rather from the json in SoftwareExplore.vue
What the license agreement looks like:
What the download page looks like:
=> Software license request & download flow

src/components/PageLayout/Navbar/Navbar.vue, src/locales/en.json
=> Add explicit home link in navigation menu

src/components/PageLayout/Comment.vue, src/components/PageLayout/Navbar/Navbar.vue, src/locales/en.json
=> Deleting comments

src/views/players/PlayerView/components/PlayerHeaderIcons.vue
Links to player certificates are shown on the user profile. They are only displayed if the user is viewing their profile. Resolves #32.
=> Links to certificate in player profile

src/views/about/About.vue, src/views/about/AboutPublicationCard.vue
* Combine player and researcher publications on About page to ensure we always reflect the most recent publications.
=> read from researcher and player pubs on about page

src/views/calendar/Calendar.vue, src/views/home/PlayerHome/PlayerHome.vue, src/views/home/PlayerHome/components/activities/NewsActivity.vue
Add news and calendar items to the home page for logged in users.
=> Landing page

package-lock.json, package.json, src/types/common-types.ts, src/views/players/PlayerView/PlayerView.vue, src/views/players/PlayerView/components/AchievementCard.vue
Change achievements page on player profile to show every achievement available in grayscale, with unlocked achievements in color.
=> Achievements

src/views/collections/CreateCollection/components/CollectionPuzzles.vue
=> Fix puzzle searching on collections

package-lock.json, package.json, src/components/PageLayout/Navbar/Navbar.vue, src/locales/en.json, src/router.ts, src/types/common-types.ts, src/utils/utils.ts, src/views/about/About.vue, src/views/scripts/ScriptDocs/ScriptDocs.vue, src/views/scripts/ScriptEdit/ScriptEdit.vue, src/views/scripts/ScriptExplore/ScriptExplore.vue, src/views/scripts/ScriptExplore/components/ScriptCard.vue, src/views/scripts/ScriptView/ScriptView.vue, src/views/scripts/ScriptView/components/CodeMirror.vue, src/views/scripts/components/CodeMirror.vue
=> Reimplement script pages
